payment.not.configured=No payment modules configured
payment.type.CREDITCARD=Credit card
payment.type.STRIPE=Credit card
payment.type.STRIPE3=Credit card
module.payment.stripe=Stripe
module.payment.stripe3=Stripe V3 (3DSecure support - requires Webhook)

module.payment.transactiontype=Transaction type
module.payment.transactiontype.preauth=Pre-authorization
module.payment.transactiontype.capture=Capture
module.payment.transactiontype.sale=Sale
module.payment.transactiontype.refund=Refund
