##
## db config
##

#Need to run these commands before running shopizer - choose your username and password
#mysql>CREATE DATABASE SALESMANAGER;
#mysql>CREATE USER shopizer IDENTIFIED BY 'very-long-shopizer-password';
#mysql>GRANT ALL ON SALESMANAGER.* TO shopizer;
#mysql>FLUSH PRIVILEGES;

db.jdbcUrl=jdbc:mysql://terraform-20250101065353493000000006.cluamaeiydc7.us-east-2.rds.amazonaws.com:3306/SALESMANAGER?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
db.user=shopizer
db.password='very-long-shopizer-password'
db.driverClass=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect


db.show.sql=true
db.preferredTestQuery=SELECT 1
db.schema=SALESMANAGER
hibernate.hbm2ddl.auto=update



##
## configuration pooling base de donn\uFFFDes
##
db.initialPoolSize=8
db.minPoolSize=8
db.maxPoolSize=15